# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Currencies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currencies
  pod 'SnapKit'
  pod 'Swinject'
  pod 'Moya'

  target 'CurrenciesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'KIF'
  end

  target 'CurrenciesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
